/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AzChat {
        "toggle": () => Promise<void>;
    }
    interface AzRoomChat {
    }
    interface AzRoomList {
        "name": string;
    }
}
declare global {
    interface HTMLAzChatElement extends Components.AzChat, HTMLStencilElement {
    }
    var HTMLAzChatElement: {
        prototype: HTMLAzChatElement;
        new (): HTMLAzChatElement;
    };
    interface HTMLAzRoomChatElement extends Components.AzRoomChat, HTMLStencilElement {
    }
    var HTMLAzRoomChatElement: {
        prototype: HTMLAzRoomChatElement;
        new (): HTMLAzRoomChatElement;
    };
    interface HTMLAzRoomListElement extends Components.AzRoomList, HTMLStencilElement {
    }
    var HTMLAzRoomListElement: {
        prototype: HTMLAzRoomListElement;
        new (): HTMLAzRoomListElement;
    };
    interface HTMLElementTagNameMap {
        "az-chat": HTMLAzChatElement;
        "az-room-chat": HTMLAzRoomChatElement;
        "az-room-list": HTMLAzRoomListElement;
    }
}
declare namespace LocalJSX {
    interface AzChat {
    }
    interface AzRoomChat {
    }
    interface AzRoomList {
        "name"?: string;
    }
    interface IntrinsicElements {
        "az-chat": AzChat;
        "az-room-chat": AzRoomChat;
        "az-room-list": AzRoomList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "az-chat": LocalJSX.AzChat & JSXBase.HTMLAttributes<HTMLAzChatElement>;
            "az-room-chat": LocalJSX.AzRoomChat & JSXBase.HTMLAttributes<HTMLAzRoomChatElement>;
            "az-room-list": LocalJSX.AzRoomList & JSXBase.HTMLAttributes<HTMLAzRoomListElement>;
        }
    }
}
